# File .chipperci.yml, which goes in the root of your repository
version: 1

environment:
  php: 8.1
  node: 18

services:
 - mysql: 5.7

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.ci .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate

  - name: Compile Dev Assets
    cmd: |
      npm ci --no-audit
      npm run build

  - name: Code Quality
    cmd: |
      ./vendor/bin/pint --test
      ./vendor/bin/phpstan analyse

  - name: Run Tests
    cmd: |
      mysql -e "grant all privileges on *.* to chipperci@'%' with grant option;"
      php artisan test --parallel